import Foundation

// MARK: - SAS Word List

struct SASWordList {
    static let words: [String] = [
        "able", "acid", "aged", "also", "area", "army", "away", "baby", "back", "ball",
        "band", "bank", "base", "bath", "bear", "beat", "been", "beer", "bell", "belt",
        "best", "bike", "bill", "bird", "blow", "blue", "boat", "body", "bomb", "bone",
        "book", "boom", "born", "boss", "both", "bowl", "bulk", "burn", "bush", "busy",
        "call", "calm", "came", "camp", "card", "care", "case", "cash", "cast", "cell",
        "chat", "chip", "city", "club", "coal", "coat", "code", "cold", "come", "cook",
        "cool", "copy", "core", "corn", "cost", "crew", "crop", "dark", "data", "date",
        "dawn", "days", "dead", "deal", "dear", "debt", "deep", "deny", "desk", "dial",
        "dice", "died", "diet", "disk", "done", "door", "dose", "down", "draw", "drew",
        "drop", "drug", "dual", "duck", "dull", "dust", "duty", "each", "earn", "ease",
        "east", "easy", "edge", "else", "even", "ever", "evil", "exit", "face", "fact",
        "fail", "fair", "fall", "farm", "fast", "fate", "fear", "feed", "feel", "feet",
        "fell", "felt", "file", "fill", "film", "find", "fine", "fire", "firm", "fish",
        "five", "flag", "flat", "flew", "flow", "food", "foot", "ford", "form", "fort",
        "four", "free", "from", "fuel", "full", "fund", "gain", "game", "gate", "gave",
        "gear", "gene", "gift", "girl", "give", "glad", "goal", "goes", "gold", "golf",
        "gone", "good", "grab", "gray", "grew", "grid", "grow", "gulf", "hair", "half",
        "hall", "hand", "hang", "hard", "harm", "hate", "have", "head", "hear", "heat",
        "held", "hell", "help", "here", "hero", "hide", "high", "hill", "hint", "hire",
        "hold", "hole", "holy", "home", "hope", "host", "hour", "huge", "hung", "hunt",
        "hurt", "idea", "inch", "into", "iron", "item", "jail", "jane", "jazz", "join",
        "jump", "june", "jury", "just", "keep", "kent", "kept", "kick", "kill", "kind",
        "king", "knee", "knew", "know", "lack", "lady", "laid", "lake", "land", "last",
        "late", "lead", "left", "less", "life", "lift", "like", "line", "link", "list",
        "live", "load", "loan", "lock", "long", "look", "lord", "lose", "loss", "lost",
        "love", "luck", "made", "mail", "main", "make", "male", "mall", "many", "mark",
        "mass", "mate", "math", "meal", "mean", "meat", "meet", "menu", "mere", "mile",
        "milk", "mind", "mine", "miss", "mode", "mood", "moon", "more", "most", "move",
        "much", "must", "name", "navy", "near", "neck", "need", "news", "next", "nice",
        "nine", "node", "none", "noon", "norm", "nose", "note", "noun", "null", "nuts",
        "okay", "once", "only", "open", "oral", "over", "pace", "pack", "page", "paid",
        "pain", "pair", "palm", "park", "part", "pass", "past", "path", "peak", "pick",
        "pile", "pink", "pipe", "plan", "play", "plot", "plug", "plus", "poll", "pool",
        "poor", "port", "post", "pull", "pure", "push", "quit", "race", "rail", "rain",
        "rank", "rare", "rate", "read", "real", "rear", "rely", "rent", "rest", "rich",
        "ride", "ring", "rise", "risk", "road", "rock", "role", "roll", "roof", "room",
        "root", "rope", "rose", "rule", "runs", "safe", "said", "sail", "sale", "salt",
        "same", "sand", "save", "seat", "seed", "seek", "seem", "seen", "self", "sell",
        "send", "sent", "ship", "shop", "shot", "show", "shut", "sick", "side", "sign",
        "sing", "sink", "site", "size", "skin", "slip", "slow", "snap", "snow", "soap",
        "soft", "soil", "sold", "sole", "some", "song", "soon", "sort", "soul", "soup",
        "spin", "spot", "star", "stay", "step", "stop", "such", "suit", "sure", "swim",
        "take", "tale", "talk", "tall", "tank", "tape", "task", "team", "tech", "tell",
        "tend", "term", "test", "text", "than", "that", "them", "then", "they", "thin",
        "this", "thus", "tide", "tied", "ties", "time", "tiny", "tips", "tire", "told",
        "tone", "took", "tool", "tops", "tour", "town", "tree", "trip", "true", "tune",
        "turn", "twin", "type", "unit", "upon", "used", "user", "uses", "vary", "vast",
        "very", "vice", "view", "vote", "wage", "wait", "wake", "walk", "wall", "want",
        "ward", "warm", "warn", "wash", "wave", "ways", "weak", "wear", "week", "well",
        "went", "were", "west", "what", "when", "wide", "wife", "wild", "will", "wind",
        "wine", "wing", "wire", "wise", "wish", "with", "wood", "word", "work", "worn",
        "yard", "yeah", "year", "your", "zero", "zone"
    ]
}